### Importing required packages:

In [ ]:
import torch
print(torch.__version__)

2.10.0+cpu


## Introduction
### Creating Tensors:
Pytorch Tensors are created using torch.Tensor()

In [10]:
# Scalar:
scalar = torch.tensor(7)
scalar

tensor(7)

In [11]:
scalar.ndim

0

In [12]:
# Get tensor back as pyton integer
scalar.item()

7

In [13]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [14]:
vector.ndim

1

In [15]:
vector.shape

torch.Size([2])

In [16]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [17]:
MATRIX.ndim

2

In [35]:
print(MATRIX[0])
print(MATRIX[1])

tensor([7, 8])
tensor([ 9, 10])


In [18]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([
                        [
                            [1,2,3],
                            [7,2,1],
                        ],
                        
                        [
                            [2,6,5],
                            [0,1,3],
                        ]
                    ])

In [25]:
TENSOR.ndim

3

In [29]:
TENSOR.shape

torch.Size([2, 2, 3])

In [34]:
print(TENSOR[0])
print(TENSOR[1])

tensor([[1, 2, 3],
        [7, 2, 1]])
tensor([[2, 6, 5],
        [0, 1, 3]])


### Summary:

In [ ]:
'''
Name	      What is it?	    Number of dimensions	Lower or upper (usually/example) scalar	    a single number	              0	                        Lower (a)
vector	  a number with direction 	     1	                        Lower (y)
matrix	  a 2-dimensional array	         2	                        Upper (Q)
tensor	  an n-dimensional array		 n                          Upper (X)

-----------------------------------------------------------------------------------------

Attribute                                   Function
.tensor()                          Creates a tensor of n dimension
.ndim                           returns the no. of dimensions of a tensor
.shape               returns the size and shape of the tensor(e.g. 2x2, 3x3, 1x2x2, etc.)
.item()                         converts the tensor into python integer

------------------------------------------------------------------------------------------

Question:
Why are 0 and 1 dimensional tensors(i.e. scalar and vectors) written in small letters(e.g. scalar = torch.tensor(7) and vector = torch.tensor([1,2])), while 2 and more dimensional(e.g. Matrices) tensors are written in capital letters(e.g. MATRIX = torch.tensor([[1,2]]))?

Answer:
It's just a notational trick. Mathematicians denoted 0-D and 1-D arrays/tensors with small letters and arrays/tensors with more dimensions with capital letters for clarity. There is no problem if you denote a matrix or any higher dimensional tensor with small letters. Neither computers care nor PyTorch.
'''