In [ ]:
import torch

### Random Tensors

Why random Tensors?

Random tensors are important because the way many neural netowrks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...`

In [56]:
# Create a random tensor of size (3,4):
random_tensor = torch.rand(3,5)
random_tensor

tensor([[0.8930, 0.8058, 0.9805, 0.7172, 0.1431],
        [0.6308, 0.4299, 0.6396, 0.2662, 0.2881],
        [0.6542, 0.4977, 0.7289, 0.5664, 0.6269]])

In [9]:
random_tensor.ndim

3

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224)) # color channels (r,g,b), Heigt, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

##### Exercise

In [18]:
TENSOR = torch.rand(1,2,3,4)
print(TENSOR)
print(f"\nNumber of Dimensions of Tensor : {TENSOR.ndim}")

tensor([[[[0.2792, 0.8682, 0.2230, 0.8665],
          [0.1877, 0.2762, 0.6886, 0.5685],
          [0.1166, 0.8833, 0.6623, 0.9414]],

         [[0.5180, 0.9354, 0.2073, 0.9235],
          [0.9097, 0.0204, 0.6733, 0.3815],
          [0.1310, 0.5518, 0.4437, 0.5903]]]])

Number of Dimensions of Tensor : 4


In [24]:
IMAGE_TENSOR = torch.rand(size=(100, 100, 3))
IMAGE_TENSOR, IMAGE_TENSOR.shape, IMAGE_TENSOR.dtype

(tensor([[[9.5094e-01, 2.2106e-01, 1.8403e-01],
          [1.9039e-01, 9.5853e-01, 9.8348e-01],
          [4.3514e-01, 6.5978e-01, 1.3340e-01],
          ...,
          [1.5634e-01, 8.0048e-01, 8.4254e-01],
          [4.0449e-01, 4.7538e-01, 8.8501e-01],
          [1.9316e-01, 7.5047e-01, 7.5264e-01]],
 
         [[3.4811e-01, 3.1718e-01, 2.9353e-01],
          [6.6778e-01, 2.4294e-01, 2.3157e-01],
          [3.8695e-01, 2.3965e-01, 1.0054e-01],
          ...,
          [5.6377e-01, 1.5507e-01, 1.5460e-01],
          [4.8245e-01, 9.7970e-02, 5.9358e-01],
          [2.0470e-02, 7.1883e-01, 4.3202e-01]],
 
         [[7.6932e-01, 6.4043e-01, 6.5341e-01],
          [8.3906e-01, 3.6976e-01, 5.8644e-01],
          [3.4663e-01, 8.8389e-01, 5.7698e-01],
          ...,
          [8.6184e-01, 7.1923e-01, 8.5471e-01],
          [9.0812e-01, 2.8056e-01, 3.1000e-01],
          [1.5295e-01, 7.1757e-01, 8.8010e-01]],
 
         ...,
 
         [[9.6816e-01, 8.0622e-01, 4.5658e-01],
          [4.8252e

### Summary:

In [ ]:
"""
Random Tensors are used because it's very tiring to right tensors(to train your model) by hand. One can create these random tensors and let the model train. The model will automatically adjust the parameters.

----------------------------------------------------------------------------------------------

    Attribute                                    Function
torch.rand(*size)                   Creates a random Tensor of the given size  
    .dtype                   Returns the type of the data(e.g. float, integer, etc.)

----------------------------------------------------------------------------------------------

When Creating a tensor for image, the number of dimensions is 3.
Image_Tensor = (h, b, c) -> Example
h = height
b = breadth
c = color channels (e.g. red, green, blue)

----------------------------------------------------------------------------------------------

Question:
Is there any difference between writing -
TENSOR = torch.rand(3,4)
and
TENSOR = torch.rand(size=(3,4))
and 
TENSOR = torch.rand(*(3,4))?

Answer:
No. All results same.
Note - Using '*' might be useful in cases like:
        shape = (3,4)
        TENSOR = torch.rand(*shape)
"""