In [1]:
import torch

### Zeros and ones

In [2]:
# Creating a random tensor
random_tensor = torch.rand(size = (3,4))
print(random_tensor)
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
print(zeros)

tensor([[0.9130, 0.3860, 0.3450, 0.0274],
        [0.2564, 0.8438, 0.2364, 0.7537],
        [0.1012, 0.5143, 0.2896, 0.0809]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [3]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [4]:
# Creating a tensor of all ones
ones = torch.ones(size=(3,4))
print(ones)
print(ones.dtype)
print(ones*random_tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.float32
tensor([[0.9130, 0.3860, 0.3450, 0.0274],
        [0.2564, 0.8438, 0.2364, 0.7537],
        [0.1012, 0.5143, 0.2896, 0.0809]])


### Summary:

In [5]:
'''
Date - 14/Mar/2026

-----------------------------------------------------------------------------------------------
    Attribute                                              Function
torch.zeroes(size=)                    Creates a tensor full of zeroes with the given size
torch.ones(size=)                        Creates a tensor full of ones with the given size

------------------------------------------------------------------------------------------------

Question: 
Why use them?

Answer:
Sometimes while writing algorithms, you need to make such tensors(full of zeroes or full of ones).
'''        

'\nDate - 14/Mar/2026\n\n-----------------------------------------------------------------------------------------------\n    Attribute                                              Function\ntorch.zeroes(size=)                    Creates a tensor full of zeroes with the given size\ntorch.ones(size=)                        Creates a tensor full of ones with the given size\n\n------------------------------------------------------------------------------------------------\n\nQuestion: \nWhy use them?\n\nAnswer:\nSometimes while writing algorithms, you need to make such tensors(full of zeroes or full of ones).\n'

### Creating a range of tensors and tensors-like

In [6]:
# Use torch.range() and get a deprecated message, use torch.arange()
one_to_ten = torch.range(start=0,end=10, step=2)
print(one_to_ten)
torch.arange(0,100,5)

tensor([ 0.,  2.,  4.,  6.,  8., 10.])


C:\Users\user\AppData\Local\Temp\ipykernel_6888\3653020371.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  one_to_ten = torch.range(start=0,end=10, step=2)


tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
        90, 95])

In [7]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [8]:
# Creating tensors-like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros
# It creates a tensor full of zeroes but as the same shape as the input

tensor([0., 0., 0., 0., 0., 0.])

In [9]:
ten_ones = torch.ones_like(input=one_to_ten)
ten_ones

tensor([1., 1., 1., 1., 1., 1.])

### Summary:

In [10]:
'''
Date - 14/Mar/2026
------------------------------------------------------------------------------------------------

          Attribute                                       Function
torch.range(start=,end=,step=)     Creates a tensor of the given range(start->end) with the  
                                                         given step
torch.zeros_like(input=)           Creates a tensor full of zeroes with the same shape as the
                                                        input tensor
torch.ones_like(input=)              Creates a tensor full of ones with the same shape as the
                                                        input tensor
'''

'\nDate - 14/Mar/2026\n------------------------------------------------------------------------------------------------\n\n          Attribute                                       Function\ntorch.range(start=,end=,step=)     Creates a tensor of the given range(start->end) with the  \n                                                         given step\ntorch.zeros_like(input=)           Creates a tensor full of zeroes with the same shape as the\n                                                        input tensor\ntorch.ones_like(input=)              Creates a tensor full of ones with the same shape as the\n                                                        input tensor\n'

### Tensor Datatypes
**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:

    1. Tensors not right datatype
    2. Tensors not right shape
    3. Tensors not on the right device

In [11]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype = None, # What datatype is the tensor (e.g. float32 or float 16)
                               device=None, # What device is your tensor on (e.g. CPU, GPU, or TPU)
                               requires_grad=False) # Whether or not to track gradients with these tensor operations.
float_32_tensor, float_32_tensor.dtype

(tensor([3., 6., 9.]), torch.float32)

In [12]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [13]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
float_32_tensor = torch.tensor([3,6,9] , dtype=torch.float32)
int_32_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [14]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.long)
float_32_tensor = torch.tensor([3,6,9] , dtype=torch.float32)
int_32_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### Summary:

In [15]:
'''
Date - 14/Mar/2026
----------------------------------------------------------------------------------------------

      Parameters                                       Meaning
        dtype                  Tells the type of the tensor (e.g. float32, float or float64)
        device                      Selects the device for computation (e.g. CPU or GPU)
    requires_grad                if True, operations performed on the tensor are recorded 

      Attribute                                 Function
      x.type(z)                   Creates a copy of tensor x of type z
      torch.long      Converts tensor data to 64-bit signed integers (long integers).

'''

'\nDate - 14/Mar/2026\n----------------------------------------------------------------------------------------------\n\n      Parameters                                       Meaning\n        dtype                  Tells the type of the tensor (e.g. float32, float or float64)\n        device                      Selects the device for computation (e.g. CPU or GPU)\n    requires_grad                if True, operations performed on the tensor are recorded \n\n      Attribute                                 Function\n      x.type(z)                   Creates a copy of tensor x of type z\n      torch.long      Converts tensor data to 64-bit signed integers (long integers).\n\n'