In [3]:
import torch

### Manipulating Tensors

Tensor operations incude:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [ ]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [5]:
# Multiplying tensor by 10
tensor *10

tensor([10, 20, 30])

In [6]:
# subtract 10
tensor - 10

tensor([-9, -8, -7])

In [65]:
# Try out PyTorch in-built functions
torch.mul(10, tensor)

tensor([10, 20, 30])

In [8]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix Multiplication:

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

In [9]:
# Element-wise multiplication
print(f"{tensor} * {tensor} = {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3]) = tensor([1, 4, 9])


In [10]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [55]:
%%time
value = 0
for i in range(len(tensor)):
    value += (tensor[i])**2
print(value)


tensor(14)
CPU times: total: 0 ns
Wall time: 1.22 ms


In [56]:
%%time
torch.matmul(tensor,tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

### Summary:

Date - 16/Mar/2026

------------------------------------------------------------------------------------------------

Function                                    What it does
torch.mul(a, b)        Multiplies the tensor a(or b) with the tensor(or scalar) b(or a)    
                                    Scalar multiplication
torch.add(a,b)         Adds a and b (whether they are scalar or tensor. If tensor, then it will
                                    add the corresponding values)
torch.matmul(a,b)           Used for Matrix multiplication between two matrices
%%time                        Returns the time taken for a block to execute

------------------------------------------------------------------------------------------------

##### torch.mul() vs  torch.matmul():
Let tensor = torch.tensor([1,2,3])

Then:<br>
torch.mul(tensor, tensor) = tensor([1,4,9]) -> Scalar Operation<br>
torch.matmul(tensor,tensor) = tensor(14) -> Matrix multiplication