In [1]:
import torch

### One of the most common errors in deep learning: shape error

In [ ]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                        [2,3],
                        [3,4]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [12, 13]])
# It will throw a shape error
torch.mm(tensor_A, tensor_B) # torch.mm = torch.matmul

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [4]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using transpose

A **transpose** switches the axes or dimensions of a given tensor

In [8]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8, 12],
         [10, 11, 13]]),
 torch.Size([2, 3]))

In [11]:
# The matrix multiplication operation works when Tensor_b is transposed
print(f"Original shapes : tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape}, tensor_b = {tensor_B.T.shape}")
print(f"Multiplying : {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes : tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]), tensor_b = torch.Size([2, 3])
Multiplying : torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[27, 30, 38],
        [44, 49, 63],
        [61, 68, 88]])

Output shape: torch.Size([3, 3])


In [13]:
tensor_A.T, tensor_A.shape, tensor_A.T.shape

(tensor([[1, 2, 3],
         [2, 3, 4]]),
 torch.Size([3, 2]),
 torch.Size([2, 3]))

In [ ]:
tensor_C = torch.tensor([
                          [
                            [1,2,3],
                            [4,5,6]
                          ]
                        ])
tensor_C.shape, tensor_C.T.shape

(torch.Size([1, 2, 3]), torch.Size([3, 2, 1]))

### Summary

Date - 18/Mar/2026

--------------------------------------------------------------------------------------------------
<pre>
Functions                                          Meaning

tensor.T               Flips the shape of a tensor(e.g. if a tensor has the shape of (1,2,3),
                                  then it will make it the shape of (3,2,1))

torch.mm(A, B)             Same as torch.matmul(). It is used for matrix multiplication
</pre>