In [154]:
import torch

### Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshape an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor.
* stacking - combine multiple tensors on top of each other (vstack) or side by side
* Squeeze - removes all 1 dimensions from a tensor
* Unsqueeze - add a 1 dimension to a target tensor
* Permute - return a view of the input with dimensions permuted(swapped) in a certain way.

In [155]:
x = torch.arange(1., 11.)
x, x.shape, x.dim()

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 torch.Size([10]),
 1)

In [156]:
# Add an extra dimension

x_reshaped = x.reshape(5,2)
print(x_reshaped, x_reshaped.shape)

print("\n")

x_reshaped_2 = x.reshape(2,5)
print(x_reshaped_2, x_reshaped_2.shape)

# x_reshaped_3 = x.reshape(1,7)
# print(x_reshaped_3, x_reshaped_3.shape) # -> This will throw error because 1*7 != 10(which is the size of the tensor x)

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]]) torch.Size([5, 2])


tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]]) torch.Size([2, 5])


In [157]:
# Changing the view
z = x.view(1,10)
z, z.shape, x

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]),
 tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [158]:
# Changing z changes x (because a view of a tensor shares the same memory as the original tensor)
z[:, 0] = 5
z,x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [159]:
# Stack tensors on top of each other
x_stacked =torch.stack([x,x,x,x], dim=0) # hstack
print(x_stacked, x_stacked.shape)

print("\n")

x_stacked_2 =torch.stack([x,x,x,x], dim=1) # vstack
print(x_stacked_2, x_stacked_2.shape)

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]) torch.Size([4, 10])


tensor([[ 5.,  5.,  5.,  5.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]]) torch.Size([10, 4])


In [160]:
x = torch.tensor([[1,2,3]]) # 2d tensor
print(torch.hstack((x,x,x,x)), torch.vstack((x,x,x,x)))
print(torch.stack([x,x,x,x], dim=0), torch.stack([x,x,x,x], dim = 1))

tensor([[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]]) tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])
tensor([[[1, 2, 3]],

        [[1, 2, 3]],

        [[1, 2, 3]],

        [[1, 2, 3]]]) tensor([[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]]])


In [161]:
[   
    [
        [1, 2, 3]
    ],
    
    [
        [1, 2, 3]
    ],
                                  # dim=0
    [
        [1, 2, 3]
    ],
    
    [
        [1, 2, 3]
    ]
]


[
    [
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],       # dim=1
        [1, 2, 3]
    ]
]

[[[1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3]]]

### Summary:
Date - 21/Mar/2026

--------------------------------------------------------------------------------------------------
<pre>
Functions                                        Meaning
.reshape()                        Changes the shape of the input tensor
.view()             Same as .reshape(), but the memory is same, i.e. changing it will change the 
                                              original tensor
.stack()                               Stack tensors upon each other
torch.hstack()                       Arranges the tensor horizontally
torch.vstack()                        Arranges the tensor vertically
</pre>