In [2]:
import torch

### Indexing (Selecting data from tensors)

In [42]:
x = torch.arange(1,19).reshape(2,3,3)
x, x.shape

(tensor([[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9]],
 
         [[10, 11, 12],
          [13, 14, 15],
          [16, 17, 18]]]),
 torch.Size([2, 3, 3]))

In [51]:
print(x[0])
print(x[0,0])
print(x[0,0,0])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3])
tensor(1)


In [ ]:
# For better visualization

x = [
        [
            [1,2,3],
            [4,5,6],
            [7,8,9]
        ],
                
        [
            [10,11,12],
            [13,14,15],
            [16,17,18]
        ]
    ]

In [ ]:
print(x[:])
print(x[:, 0])
print("\n")
print(x[0, 0])
print("\n")
print(x[0,0,:])

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])
tensor([[ 1,  2,  3],
        [10, 11, 12]])


tensor([1, 2, 3])


tensor([1, 2, 3])


### Summary:
Date - 23/Mar/2026

--------------------------------------------------------------------------------------------------
<pre>
Understand how the semicolon(:) in indexing actually works:

Suppose you have a list L with two elements:
L = [A, B]
so writing L[:] means take everything present inside L(i.e. A and B), and print them with an extra square bracket.

print(L) -> [A,B] (instead of just - A,B - i.e. without square brackets)

Now let's suppose that elements A and B are themselves matrices of shape - 3*3 (as we saw above in the code).

So writing L[:, 0] means take everything form L(i.e. A and B), and print the first row of every element you took...

So L[:,0] -> A[0] and B[0]

Now suppose you write - L[:,0,0]...
This will print the first element of the first row in both A and B...

If you have a tensor with a lots of elements, like A - Z... and you wanna print the certain row of every element (or a certain element of a certain row of every element), then you can use this method.

Instead of writing:
A[0][0], B[0][0], C[0][0], D[0][0]...Z[0][0]

You can write:
L[:,0,0]
</pre>