In [80]:
import torch
import numpy as np

### Pytorch tensors & NumPy
--------------------------------------------------------------------------------------------------

NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> torch.from_numpy(ndarray)
* PyTorch tensor -> NumPy -> torch.Tensor.numpy()

In [81]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [82]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float32)

In [83]:
torch.arange(1.0,8.0).dtype

torch.float32

In [84]:
array = array + 1
array, tensor
# Note :- While using numpy, if you change an array, then the tensor(which is the same version of that NumPy array) will not change

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [85]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [86]:
numpy_tensor.dtype
# Note :-
# default dtype for torch.tensor -> float 64
# default dtype for numpy.array -> float32

dtype('float32')

In [87]:
tensor = tensor + 1 # Writing tensor += 1 will change the numpy_tensor
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Summary:
Date - 24/Mar/2026

--------------------------------------------------------------------------------------------------
<pre>
Function                                                Meaning
torch.from_numpy(array)              Converts the array into a tensor (of Pytroch)
tensor.numpy()                        Converts the tensor into an array (of NumPy)
</pre>
--------------------------------------------------------------------------------------------------
##### Why 'tensor = tensor + 1' != 'tensor += 1'?
<pre>
When you write:
    tensor = tensor + 1
It creates a new variable (it uses new memory)

But when you write:
    tensor += 1
It just changes the existing memory (instead of creating a new variable).
</pre>

##### Proof:



In [88]:
print(id(tensor))
tensor = tensor + 1
print(f"{id(tensor)} -> different")  # different

tensor = torch.ones(7)
print(id(tensor))
tensor += 1
print(f"{id(tensor)} -> Same as above")  # same

2084047967312
2083924900944 -> different
2084071461808
2084071461808 -> Same as above
