In [69]:
import torch

### Reproducibility (trying to take random of random)

In short how a neural network w learns:

`start with random numbers -> tensor operations -> update random number to try and make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comess from the concept of a **random seed.**

Essentially what the random seed does is "flavour" the randomness.

In [70]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])
tensor([[0.1053, 0.2695, 0.3588, 0.1994],
        [0.5472, 0.0062, 0.9516, 0.0753],
        [0.8860, 0.5832, 0.3376, 0.8090]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random but reproducible tensors

RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED) 
# Note :- you have to set random_seed 2 times... If you don't, then the two tensors will not be equal. This is because setting manual_seed to some value tells PyTorch that you have to start the random number generator from here, and as you intialize more tensors, they will be different because the random seed gets slightly increased after every intialization. that's why if you set the manual_seed only once and then intialize 2 tensors... Then both of the tensors will be different but they will never change doesn't matter how many times you run the code... They will be the exact same everytime.
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


### Summary:
Date - 25/Mar/2026

--------------------------------------------------------------------------------------------------
<pre> 
      Function                               Meaning
torch.manual_seed(seed=)      Sets the random seed to the given input
</pre>
--------------------------------------------------------------------------------------------------
##### What special about random seed 42?
**There was a book [_The Hitchhiker's Guide to the Galaxy_](https://en.wikipedia.org/wiki/The_Hitchhiker%27s_Guide_to_the_Galaxy) by [_Douglas Adams_](https://en.wikipedia.org/wiki/Douglas_Adams). It portrayed a computer who computed the answer of life, universe, and everything for millions of years.. And at last... it answered... 42.**<br><br>
**Douglas Adams just added it randomly as a joke with no explanation. After this programmers started to use it as a joke... or say... meme. Just like Douglas Adams put this number randomly, they use it for random seed. It's popular!**<br><br>
**[Random seed 42](https://www.kaggle.com/discussions/general/541061) doesn't have anything special mathematically so it doesn't matter whether you use it or something else... It's fun to use it just like - _Hello World!_.**

-------------------------------------------------------------------------------------------------
##### Debate on pseudorandomness:
**So there is a debate on the randomness of computers. Some people call this randomness -> [_pseudorandomness_](https://en.wikipedia.org/wiki/Pseudorandomness).**<br><br>
**This is because a computer always works in a sequence and it's imposiible for the output to be truly random. Cyptographers argue that if someone know the algorthm and the random seed, then they can easily break the encyptions.**<br><br>
**Some algorithms generate randomness based on your computer time, while some use a formula and random seeds.**<br><br>
**For now, it's almost impossible for a computer to generate true random numbers. This is because every random output is technically predictable**