In [27]:
import torch

### 3. Putting tensors (and models) on the GPU
The reason we want out tensors/models on the GPU is because using a GPU results in faster computations.

In [28]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1,2,3], device="cpu")

#Tensor on the GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [29]:
device = "cuda" if torch.cuda.is_available() else "cpu"
tensor_on_gpu = tensor.to(device)
tensor_on_gpu, device

(tensor([1, 2, 3]), 'cpu')

### 4. Moving Tensors back to CPU

In [30]:
# If you want to use NumPy for your tensors, then you'll have to shift to CPU, because NumPy can't leverage with GPU...
tensor_on_gpu.numpy() # -> It will throw an error if you are using CUDA

array([1, 2, 3])

In [ ]:
tensor_back_on_CPU = tensor_on_gpu.cpu().numpy()
tensor_back_on_CPU

array([1, 2, 3])

### Summary:
Date - 27/Mar/2026

--------------------------------------------------------------------------------------------------
  Function                                       Meaning
tensor.to(device)             Moves the tensor to the selected device (e.g. GPU)
tensor.cpu()                   Moves the tensor from its current device to CPU  
tensor.numpy()                      Converts the tensor to a numpy array 

--------------------------------------------------------------------------------------------------
##### Why we can't use NumPy on GPU?
This is because NumPy was made in simpler and older times while GPUs were made in a new era. 
<br><br>
🧠 The real reason

NumPy is designed to:

* Run on CPU only
* Use optimized CPU libraries (BLAS, LAPACK)
* Treat memory as regular RAM

GPUs? Completely different beast:

* Separate memory (VRAM)
* Different architecture (thousands of tiny cores)
* Needs special parallel code (CUDA, etc.)

Numpy just can't talk to GPUs...