In [6]:
import torch

### 3. Putting tensors (and models) on the GPU
The reason we want out tensors/models on the GPU is because using a GPU results in faster computations.

In [7]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1,2,3], device="cpu")

#Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [9]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving Tensors back to CPU

In [10]:
# If you want to use NumPy for your tensors, then you'll have to shift to CPU, because NumPy can't leverage with GPU...
tensor_on_gpu.numpy() # -> It will throw an error

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [12]:
tensor_back_on_CPU = tensor_on_gpu.cpu().numpy()
tensor_back_on_CPU, tensor_back_on_CPU.device

(array([1, 2, 3]), 'cpu')