In [37]:
import torch

### Exercises

1. Documentation reading - A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness). See the documentation on [torch.Tensor](https://docs.pytorch.org/docs/stable/tensors.html) and for [torch.cuda](https://docs.pytorch.org/docs/stable/cuda.html).

2. Create a random tensor with shape (7, 7).

In [38]:
tensor = torch.rand(7,7)
tensor

tensor([[0.5932, 0.1123, 0.1535, 0.2417, 0.7262, 0.7011, 0.2038],
        [0.6511, 0.7745, 0.4369, 0.5191, 0.6159, 0.8102, 0.9801],
        [0.1147, 0.3168, 0.6965, 0.9143, 0.9351, 0.9412, 0.5995],
        [0.0652, 0.5460, 0.1872, 0.0340, 0.9442, 0.8802, 0.0012],
        [0.5936, 0.4158, 0.4177, 0.2711, 0.6923, 0.2038, 0.6833],
        [0.7529, 0.8579, 0.6870, 0.0051, 0.1757, 0.7497, 0.6047],
        [0.1100, 0.2121, 0.9704, 0.8369, 0.2820, 0.3742, 0.0237]])

3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [39]:
tensor_1 = torch.rand(1,7).T
torch.matmul(tensor, tensor_1)

tensor([[1.2239],
        [2.0847],
        [1.9002],
        [0.9408],
        [1.5213],
        [1.3606],
        [0.8780]])

4. Set the random seed to 0 and do exercises 2 & 3 over again.


In [41]:
RANDOM_SEED = 0

torch.manual_seed(RANDOM_SEED)
tensor = torch.rand(7,7)
print(tensor)

torch.manual_seed(RANDOM_SEED)
tensor_1 = torch.rand(1,7)
print(tensor_1)
torch.matmul(tensor, tensor_1.T)

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]])


tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.

In [ ]:
seed = 1234
torch.cuda.device("cuda")
torch.manual_seed(seed)
# torch.cuda.manual_seed(seed)
tensor1 = torch.rand(7,7, device="cuda")
torch.cuda.manual_seed(seed)
tensor2 = torch.rand(7,7)
tensor1, tensor.device, tensor2

**Note:** I can't run the code because I neither have a GPU installed locally nor I am using online google colab... But here are the results when I ran the code online on colab.(Just for experiment)

--------------------------------------------------------------------------------------------------
### Result:
(tensor<br>([[0.1272, 0.8167, 0.5440, 0.6601, 0.2721, 0.9737, 0.3903],<br>
         [0.3394, 0.5451, 0.7312, 0.3864, 0.5959, 0.7578, 0.2126],<br>
         [0.7198, 0.9845, 0.5518, 0.0981, 0.0582, 0.5839, 0.1083],<br>
         [0.9461, 0.3170, 0.8328, 0.6676, 0.2886, 0.9022, 0.8115],<br>
         [0.1784, 0.9534, 0.1486, 0.3882, 0.7977, 0.1752, 0.5777],<br>
         [0.1949, 0.8499, 0.3125, 0.2156, 0.0383, 0.4934, 0.3138],<br>
         [0.3121, 0.5664, 0.1266, 0.7097, 0.0040, 0.5147, 0.2811]],<br>
        device='cuda:0'),<br><br>
 device(type='cuda', index=0),<br><br>
 tensor(<br>[[0.0290, 0.4019, 0.2598, 0.3666, 0.0583, 0.7006, 0.0518],<br>
         [0.4681, 0.6738, 0.3315, 0.7837, 0.5631, 0.7749, 0.8208],<br>
         [0.2793, 0.6817, 0.2837, 0.6567, 0.2388, 0.7313, 0.6012],<br>
         [0.3043, 0.2548, 0.6294, 0.9665, 0.7399, 0.4517, 0.4757],<br>
         [0.7842, 0.1525, 0.6662, 0.3343, 0.7893, 0.3216, 0.5247],<br>
         [0.6688, 0.8436, 0.4265, 0.9561, 0.0770, 0.4108, 0.0014],<br>
         [0.5414, 0.6419, 0.2976, 0.7077, 0.4189, 0.0655, 0.8839]]))<br><br>
We can clearly see that:
        tensor1 != tensor2

--------------------------------------------------------------------------------------------------
### Conclusion:
Using different device (e.g. CPU and CUDA) results in different random tensors evenif their random seed is exactly same.

**torch.cuda.manual_seed(x):** Sets the random seed for tensors using device = "cuda"... Rest of the tensors will be unaffected.



6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

In [ ]:
torch.manual_seed(1234)
t1 = torch.rand(2,3, device="cuda")
t2 = torch.rand(2,3, device="cuda")
t1, t2

### Result:
<pre>
(tensor([[0.1272, 0.8167, 0.5440],
         [0.6601, 0.2721, 0.9737]], device='cuda:0'),
 tensor([[0.6208, 0.0276, 0.3255],
         [0.1114, 0.6812, 0.3608]], device='cuda:0'))
</pre>

7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [ ]:
result = torch.matmul(t1, t2.T)
result
# This will throw an error because I don't have a GPU and thus didn't run the above block of code (which intializes both the tensors)... So it will throw an error saying that t1 is not defined. But if I run it online... then we will see the following output:

### Result:
<pre>
tensor([[0.2786, 0.7668],
        [0.7343, 0.6102]], device='cuda:0')
</pre>

8. Find the maximum and minimum values of the output of 7.

In [ ]:
max, min = torch.max(result), torch.min(result)
max, min

### Result:
<pre>
(tensor(0.7668, device='cuda:0'), tensor(0.2786, device='cuda:0'))
</pre>

9. Find the maximum and minimum index values of the output of 7.

In [ ]:
arg_max = torch.argmax(result)
arg_min = torch.argmin(result)
arg_max, arg_min

### Result:
<pre>
(tensor(1, device='cuda:0'), tensor(0, device='cuda:0'))
</pre>

10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape

In [47]:
torch.manual_seed(7)
t1 = torch.rand(1,1,1,7)
t2 = torch.squeeze(t1)
print(f"First Tensor:\n\n{t1}\nShape: {t1.shape}")
print(f"\nSecond Tensor:\n\n{t2}\nShape: {t2.shape}")

First Tensor:

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071]]]])
Shape: torch.Size([1, 1, 1, 7])

Second Tensor:

tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071])
Shape: torch.Size([7])
